version: '3'

services:
  recommendation:
    build: ./recommendation
    ports:
      - "5000:5000"
    links:
      - mongo
    env_file:
      - env.sh

  mongo:
    image: mongo
    env_file:
      - env.sh
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-data:/data/db"

  jupyter:
    build: ./jupyter_recommendation
    ports:
      - "8888:8888"
    links:
      - mongo
    env_file:
      - env.sh
    volumes:
      - "./jupyter_recommendation:/home/jovyan"